ConnectException caused application to hang
2019-05-08 09:32:52,858 ERROR
[executor-1][edu.stanford.irt.eresources.EresourceDatabaseException] -
EresourceDatabaseException
java.net.ConnectException: Operation timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at edu.stanford.irt.eresources.IOUtils.getStream(IOUtils.java:34)
        at edu.stanford.irt.eresources.marc.HTTPAugmentationsService.buildAugmentations(HTTPAugmentationsService.java:32)
        at edu.stanford.irt.eresources.marc.ReservesTextAugmentation.getReservesAugmentations(ReservesTextAugmentation.java:17)
        at edu.stanford.irt.eresources.marc.KeywordsStrategy.getKeywords(KeywordsStrategy.java:67)
        at edu.stanford.irt.eresources.marc.AbstractMarcEresource.getKeywords(AbstractMarcEresource.java:190)
        at edu.stanford.irt.eresources.SolrEresourceHandler.getKeywords(SolrEresourceHandler.java:243)
        at edu.stanford.irt.eresources.SolrEresourceHandler.insertEresource(SolrEresourceHandler.java:152)
        at edu.stanford.irt.eresources.SolrEresourceHandler.run(SolrEresourceHandler.java:121)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "executor-1"
edu.stanford.irt.eresources.EresourceDatabaseException:
java.net.ConnectException: Operation timed out (Connection timed out)
        at edu.stanford.irt.eresources.marc.HTTPAugmentationsService.buildAugmentations(HTTPAugmentationsService.java:36)
        at edu.stanford.irt.eresources.marc.ReservesTextAugmentation.getReservesAugmentations(ReservesTextAugmentation.java:17)
        at edu.stanford.irt.eresources.marc.KeywordsStrategy.getKeywords(KeywordsStrategy.java:67)
        at edu.stanford.irt.eresources.marc.AbstractMarcEresource.getKeywords(AbstractMarcEresource.java:190)
        at edu.stanford.irt.eresources.SolrEresourceHandler.getKeywords(SolrEresourceHandler.java:243)
        at edu.stanford.irt.eresources.SolrEresourceHandler.insertEresource(SolrEresourceHandler.java:152)
        at edu.stanford.irt.eresources.SolrEresourceHandler.run(SolrEresourceHandler.java:121)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Operation timed out (Connection
timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at edu.stanford.irt.eresources.IOUtils.getStream(IOUtils.java:34)
        at edu.stanford.irt.eresources.marc.HTTPAugmentationsService.buildAugmentations(HTTPAugmentationsService.java:32)
        ... 9 more