oracle connection leak causing intermittent errors (see below)
edu.stanford.irt.eresources.EresourceDatabaseException:
java.sql.SQLException: Listener refused the connection with the
following error:
ORA-12519, TNS:no appropriate service handler found

        at
edu.stanford.irt.eresources.EresourceInputStream.run(EresourceInputStream.java:66)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Listener refused the connection with
the following error:
ORA-12519, TNS:no appropriate service handler found

        at
oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:458)
        at
oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:546)
        at
oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:236)
        at
oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
        at
oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:521)
        at
oracle.jdbc.pool.OracleDataSource.getPhysicalConnection(OracleDataSource.java:280)
        at
oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:207)
        at
oracle.jdbc.pool.OracleDataSource.getConnection(OracleDataSource.java:157)
        at
edu.stanford.irt.eresources.EresourceInputStream.run(EresourceInputStream.java:42)
        ... 3 more
Caused by: oracle.net.ns.NetException: Listener refused the connection
with the following error:
ORA-12519, TNS:no appropriate service handler found

        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:395)
        at
oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1102)
        at
oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:320)
        ... 11 more