Revert "openjdk-17"
This reverts commit 60dc39dd38023129f32107187955b598d9e57aef.

AOP errors seem to correlate to this commit

Caused by: org.springframework.aop.framework.AopConfigException:
Unexpected AOP exception; nested exception is
java.lang.NullPointerException: Cannot invoke "Object.getClass()"
because "cause" is null