lots of errors running via Docker; spring boot dependency simplification
seeing errors like this one:
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context
with path [] threw exception [Handler processing failed:
java.lang.NoClassDefFoundError:
org/springframework/web/servlet/ModelAndViewDefiningException] with root
cause
java.lang.ClassNotFoundException:
org.springframework.web.servlet.ModelAndViewDefiningException